<a href="https://colab.research.google.com/github/umeshgurjar914042-creator/sql-practice/blob/main/sql_basics_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

   id    name   dept  salary     city
0   1    Ravi  Sales   30000  Lucknow
1   2   Anita     IT   50000    Delhi
2   3  Suresh     IT   45000  Lucknow
3   4   Meena     HR   35000    Delhi
4   5   Karan  Sales   28000   Mumbai
5   6   Pooja     IT   60000   Mumbai

     name  salary
0   Anita   50000
1  Suresh   45000
2   Pooja   60000